openapi: 3.0.0
info:
  description: "API for Chargeable Party management.  \nÂ© 2022, 3GPP Organizational\
    \ Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  \nAll rights reserved.\n"
  title: 3gpp-chargeable-party
  version: 1.2.1
externalDocs:
  description: 3GPP TS 29.122 V17.7.0 T8 reference point for Northbound APIs
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.122/
servers:
- url: "{apiRoot}/3gpp-chargeable-party/v1"
  variables:
    apiRoot:
      default: https://example.com
      description: apiRoot as defined in clause 5.2.4 of 3GPP TS 29.122.
security:
- {}
- oAuth2ClientCredentials: []
paths:
  /{scsAsId}/transactions:
    get:
      operationId: FetchAllChargeablePartyTransactions
      parameters:
      - description: Identifier of SCS/AS
        explode: false
        in: path
        name: scsAsId
        required: true
        schema:
          type: string
        style: simple
      - content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/IpAddr'
              minItems: 1
              type: array
        description: The IP address(es) of the requested UE(s).
        in: query
        name: ip-addrs
        required: false
      - description: The IPv4 address domain identifier. The attribute may only be
          provided if IPv4 address is included in the ip-addrs query parameter.
        explode: true
        in: query
        name: ip-domain
        required: false
        schema:
          type: string
        style: form
      - description: The MAC address(es) of the requested UE(s).
        explode: true
        in: query
        name: mac-addrs
        required: false
        schema:
          items:
            $ref: '#/components/schemas/MacAddr48'
          minItems: 1
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                description: individual BDT policy subscription.
                items:
                  $ref: '#/components/schemas/ChargeableParty'
                minItems: 0
                type: array
          description: OK (successful query of Chargeable Party resource)
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "308":
          description: Permanent Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "406":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Acceptable
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
      summary: Read all or queried chargeable party transaction resources for a given
        SCS/AS.
      tags:
      - Chargeable Party Transaction Operation
    post:
      callbacks:
        eventNotification:
          '{$request.body#/notificationDestination}':
            post:
              operationId: eventNotification_Post
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/NotificationData'
                required: true
              responses:
                "204":
                  description: No Content (The successful acknowledgement of the notification)
                "307":
                  description: Temporary Redirect
                  headers:
                    Location:
                      description: An alternative URI of the resource.
                      required: true
                      schema:
                        type: string
                "308":
                  description: Permanent Redirect
                  headers:
                    Location:
                      description: An alternative URI of the resource.
                      required: true
                      schema:
                        type: string
                "400":
                  content:
                    application/problem+json:
                      schema:
                        $ref: '#/components/schemas/ProblemDetails'
                  description: Bad request
                "401":
                  content:
                    application/problem+json:
                      schema:
                        $ref: '#/components/schemas/ProblemDetails'
                  description: Unauthorized
                "403":
                  content:
                    application/problem+json:
                      schema:
                        $ref: '#/components/schemas/ProblemDetails'
                  description: Forbidden
                "404":
                  content:
                    application/problem+json:
                      schema:
                        $ref: '#/components/schemas/ProblemDetails'
                  description: Not Found
                "411":
                  content:
                    application/problem+json:
                      schema:
                        $ref: '#/components/schemas/ProblemDetails'
                  description: Length Required
                "413":
                  content:
                    application/problem+json:
                      schema:
                        $ref: '#/components/schemas/ProblemDetails'
                  description: Payload Too Large
                "415":
                  content:
                    application/problem+json:
                      schema:
                        $ref: '#/components/schemas/ProblemDetails'
                  description: Unsupported Media Type
                "429":
                  content:
                    application/problem+json:
                      schema:
                        $ref: '#/components/schemas/ProblemDetails'
                  description: Too Many Requests
                "500":
                  content:
                    application/problem+json:
                      schema:
                        $ref: '#/components/schemas/ProblemDetails'
                  description: Internal Server Error
                "503":
                  content:
                    application/problem+json:
                      schema:
                        $ref: '#/components/schemas/ProblemDetails'
                  description: Service Unavailable
                default:
                  description: Generic Error
              x-callback-request: true
      operationId: CreateChargeablePartyTransaction
      parameters:
      - description: Identifier of SCS/AS
        explode: false
        in: path
        name: scsAsId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChargeableParty'
        description: representation of the Chargeable Party resource to be Created
          in the SCEF
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargeableParty'
          description: successful creation of a chargeable party resource
          headers:
            Location:
              description: Contains the URI of the newly created resource
              explode: false
              required: true
              schema:
                type: string
              style: simple
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "411":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Length Required
        "413":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Payload Too Large
        "415":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unsupported Media Type
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
      summary: Create a new chargeable party transaction resource.
      tags:
      - Chargeable Party Transaction Operation
  /{scsAsId}/transactions/{transactionId}:
    delete:
      operationId: DeleteChargeablePartyTransaction
      parameters:
      - description: Identifier of SCS/AS
        explode: false
        in: path
        name: scsAsId
        required: true
        schema:
          type: string
        style: simple
      - description: Identifier of transaction
        explode: false
        in: path
        name: transactionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: successful deletion of an resouce of chargeable party
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationData'
          description: OK (Successful deletion of the existing subscription)
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "308":
          description: Permanent Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
      summary: Deletes a chargeable party resource for a given SCS/AS and a transcation
        Id.
      tags:
      - Individual chargeable party resource Operation
    get:
      operationId: FetchIndChargeablePartyTransaction
      parameters:
      - description: Identifier of SCS/AS
        explode: false
        in: path
        name: scsAsId
        required: true
        schema:
          type: string
        style: simple
      - description: Identifier of transaction
        explode: false
        in: path
        name: transactionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargeableParty'
          description: OK (successful query of a chargeable party resource)
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "308":
          description: Permanent Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "406":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Acceptable
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
      summary: Read a chargeable party resource for a given SCS/AS and a transaction
        Id.
      tags:
      - Individual chargeable party resource Operation
    patch:
      operationId: UpdateChargeablePartyTransaction
      parameters:
      - description: Identifier of SCS/AS
        explode: false
        in: path
        name: scsAsId
        required: true
        schema:
          type: string
        style: simple
      - description: Identifier of transaction
        explode: false
        in: path
        name: transactionId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/ChargeablePartyPatch'
        description: representation of the chargeable party resource to be udpated
          in the SCEF
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargeableParty'
          description: successful update of a chargeable party resource
        "204":
          description: No Content
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "308":
          description: Permanent Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "411":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Length Required
        "413":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Payload Too Large
        "415":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unsupported Media Type
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
      summary: Updates a existing chargeable party resource for a given SCS/AS and
        transaction Id.
      tags:
      - Individual chargeable party resource Operation
components:
  responses:
    "307":
      description: Temporary Redirect
      headers:
        Location:
          description: An alternative URI of the resource.
          required: true
          schema:
            type: string
    "308":
      description: Permanent Redirect
      headers:
        Location:
          description: An alternative URI of the resource.
          required: true
          schema:
            type: string
    "400":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Bad request
    "401":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Unauthorized
    "403":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Forbidden
    "404":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Not Found
    "406":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Not Acceptable
    "429":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Too Many Requests
    "500":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Internal Server Error
    "503":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Service Unavailable
    default:
      description: Generic Error
    "411":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Length Required
    "413":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Payload Too Large
    "415":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Unsupported Media Type
  schemas:
    ChargeableParty:
      description: Represents the configuration of a chargeable party.
      example:
        notificationDestination: notificationDestination
        snssai:
          sd: sd
          sst: 20
        supportedFeatures: supportedFeatures
        dnn: dnn
        ipDomain: ipDomain
        sponsoringEnabled: true
        websockNotifConfig:
          requestWebsocketUri: true
          websocketUri: websocketUri
        requestTestNotification: true
        flowInfo:
        - flowDescriptions:
          - flowDescriptions
          - flowDescriptions
          flowId: 6
        - flowDescriptions:
          - flowDescriptions
          - flowDescriptions
          flowId: 6
        ethFlowInfo:
        - destMacAddr: destMacAddr
          destMacAddrEnd: destMacAddrEnd
          sourceMacAddr: sourceMacAddr
          fDir: null
          ethType: ethType
          fDesc: fDesc
          vlanTags:
          - vlanTags
          - vlanTags
          srcMacAddrEnd: srcMacAddrEnd
        - destMacAddr: destMacAddr
          destMacAddrEnd: destMacAddrEnd
          sourceMacAddr: sourceMacAddr
          fDir: null
          ethType: ethType
          fDesc: fDesc
          vlanTags:
          - vlanTags
          - vlanTags
          srcMacAddrEnd: srcMacAddrEnd
        referenceId: referenceId
        usageThreshold:
          duration: 0
          totalVolume: 0
          downlinkVolume: 0
          uplinkVolume: 0
        ipv6Addr: ipv6Addr
        exterAppId: exterAppId
        servAuthInfo: null
        self: self
        ipv4Addr: ipv4Addr
        events:
        - null
        - null
        macAddr: macAddr
        sponsorInformation:
          aspId: aspId
          sponsorId: sponsorId
      properties:
        self:
          description: string formatted according to IETF RFC 3986 identifying a referenced
            resource.
          type: string
        supportedFeatures:
          description: |
            A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of "0" to "9",  "a" to "f" or "A" to "F" and shall represent the support of 4 features as described in  tableÂ 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
          pattern: "^[A-Fa-f0-9]*$"
          type: string
        dnn:
          description: |
            String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. "Label1.Label2.Label3").
          type: string
        snssai:
          $ref: '#/components/schemas/Snssai'
        notificationDestination:
          description: string formatted according to IETF RFC 3986 identifying a referenced
            resource.
          type: string
        requestTestNotification:
          description: Set to true by the SCS/AS to request the SCEF to send a test
            notification as defined in clause 5.2.5.3. Set to false or omitted otherwise.
          type: boolean
        websockNotifConfig:
          $ref: '#/components/schemas/WebsockNotifConfig'
        exterAppId:
          description: Identifies the external Application Identifier.
          type: string
        ipv4Addr:
          description: string identifying a Ipv4 address formatted in the "dotted
            decimal" notation as defined in IETF RFC 1166.
          type: string
        ipDomain:
          type: string
        ipv6Addr:
          description: string identifying a Ipv6 address formatted according to clause
            4 in IETF RFC 5952. The mixed Ipv4 Ipv6 notation according to clause 5
            of IETF RFC 5952 shall not be used.
          type: string
        macAddr:
          description: |
            String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042.
          pattern: "^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$"
          type: string
        flowInfo:
          description: Describes the application flows.
          items:
            $ref: '#/components/schemas/FlowInfo'
          minItems: 1
          type: array
        ethFlowInfo:
          description: Identifies Ethernet packet flows.
          items:
            $ref: '#/components/schemas/EthFlowDescription'
          minItems: 1
          type: array
        sponsorInformation:
          $ref: '#/components/schemas/SponsorInformation'
        sponsoringEnabled:
          description: |
            Indicates whether the sponsoring data connectivity is enabled (true) or not (false).
          type: boolean
        referenceId:
          description: string identifying a BDT Reference ID as defined in clause
            5.3.3 of 3GPP TS 29.154.
          type: string
        servAuthInfo:
          $ref: '#/components/schemas/ServAuthInfo'
        usageThreshold:
          $ref: '#/components/schemas/UsageThreshold'
        events:
          description: Represents the list of event(s) to which the SCS/AS requests
            to subscribe to.
          items:
            $ref: '#/components/schemas/Event'
          minItems: 1
          type: array
      required:
      - notificationDestination
      - sponsorInformation
      - sponsoringEnabled
      type: object
    ChargeablePartyPatch:
      description: Represents a modification request of a chargeable party resource.
      properties:
        flowInfo:
          description: Describes the IP flows.
          items:
            $ref: '#/components/schemas/FlowInfo'
          minItems: 1
          type: array
        exterAppId:
          description: Identifies the external Application Identifier.
          type: string
        ethFlowInfo:
          description: Identifies Ethernet packet flows.
          items:
            $ref: '#/components/schemas/EthFlowDescription'
          minItems: 1
          type: array
        sponsoringEnabled:
          description: |
            Indicates whether the sponsoring data connectivity is enabled (true) or not (false).
          type: boolean
        referenceId:
          description: string identifying a BDT Reference ID as defined in clause
            5.3.3 of 3GPP TS 29.154.
          type: string
        usageThreshold:
          $ref: '#/components/schemas/UsageThresholdRm'
        notificationDestination:
          description: string formatted according to IETF RFC 3986 identifying a referenced
            resource.
          type: string
        events:
          description: Represents the list of event(s) to which the SCS/AS requests
            to subscribe to.
          items:
            $ref: '#/components/schemas/Event'
          minItems: 1
          type: array
      type: object
    IpAddr:
      description: Contains an IP adresse.
      oneOf:
      - required:
        - ipv4Addr
      - required:
        - ipv6Addr
      - required:
        - ipv6Prefix
      properties:
        ipv4Addr:
          description: |
            String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
          example: 198.51.100.1
          pattern: "^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$"
          type: string
        ipv6Addr:
          $ref: '#/components/schemas/Ipv6Addr'
        ipv6Prefix:
          $ref: '#/components/schemas/Ipv6Prefix'
      type: object
    Ipv4Addr:
      description: |
        String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
      example: 198.51.100.1
      pattern: "^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$"
      type: string
    Ipv6Addr:
      allOf:
      - pattern: "^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))$"
      - pattern: "^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))$"
      description: |
        String identifying an IPv6 address formatted according to clause 4 of RFC5952. The mixed IPv4 IPv6 notation according to clause 5 of RFC5952 shall not be used.
      example: 2001:db8:85a3::8a2e:370:7334
      type: string
    Ipv6Prefix:
      allOf:
      - pattern: "^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))(\\\
          /(([0-9])|([0-9]{2})|(1[0-1][0-9])|(12[0-8])))$"
      - pattern: "^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))(\\\
          /.+)$"
      description: |
        String identifying an IPv6 address prefix formatted according to clause 4 of RFC 5952. IPv6Prefix data type may contain an individual /128 IPv6 address.
      example: 2001:db8:abcd:12::0/64
      type: string
    MacAddr48:
      description: |
        String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042.
      pattern: "^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$"
      type: string
    ProblemDetails:
      description: Represents additional information and details on an error response.
      properties:
        type:
          description: string providing an URI formatted according to IETF RFC 3986.
          type: string
        title:
          description: "A short, human-readable summary of the problem type. It should\
            \ not change from occurrence to occurrence of the problem."
          type: string
        status:
          description: The HTTP status code for this occurrence of the problem.
          type: integer
        detail:
          description: A human-readable explanation specific to this occurrence of
            the problem.
          type: string
        instance:
          description: string providing an URI formatted according to IETF RFC 3986.
          type: string
        cause:
          description: "A machine-readable application error cause specific to this\
            \ occurrence of the problem. This IE should be present and provide application-related\
            \ error information, if available."
          type: string
        invalidParams:
          description: "Description of invalid parameters, for a request rejected\
            \ due to invalid parameters."
          items:
            $ref: '#/components/schemas/InvalidParam'
          minItems: 1
          type: array
        supportedFeatures:
          description: |
            A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of "0" to "9",  "a" to "f" or "A" to "F" and shall represent the support of 4 features as described in  tableÂ 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
          pattern: "^[A-Fa-f0-9]*$"
          type: string
      type: object
    Uri:
      description: string providing an URI formatted according to IETF RFC 3986.
      type: string
    InvalidParam:
      description: "Represents the description of invalid parameters, for a request\
        \ rejected due to invalid parameters."
      properties:
        param:
          description: "Attribute's name encoded as a JSON Pointer, or header's name."
          type: string
        reason:
          description: "A human-readable reason, e.g. \"must be a positive integer\"\
            ."
          type: string
      required:
      - param
      type: object
    NotificationData:
      description: Represents the information to be conveyed in a bearer level event(s)
        notification.
      example:
        eventReports:
        - flowIds:
          - 5
          - 5
          accumulatedUsage:
            duration: 0
            totalVolume: 0
            downlinkVolume: 0
            uplinkVolume: 0
          event: null
        - flowIds:
          - 5
          - 5
          accumulatedUsage:
            duration: 0
            totalVolume: 0
            downlinkVolume: 0
            uplinkVolume: 0
          event: null
        transaction: transaction
      properties:
        transaction:
          description: string formatted according to IETF RFC 3986 identifying a referenced
            resource.
          type: string
        eventReports:
          description: Contains the reported event and applicable information
          items:
            $ref: '#/components/schemas/EventReport'
          minItems: 1
          type: array
      required:
      - eventReports
      - transaction
      type: object
    Link:
      description: string formatted according to IETF RFC 3986 identifying a referenced
        resource.
      type: string
    EventReport:
      description: Represents an event report.
      example:
        flowIds:
        - 5
        - 5
        accumulatedUsage:
          duration: 0
          totalVolume: 0
          downlinkVolume: 0
          uplinkVolume: 0
        event: null
      properties:
        event:
          $ref: '#/components/schemas/Event'
        accumulatedUsage:
          $ref: '#/components/schemas/AccumulatedUsage'
        flowIds:
          description: Identifies the IP flows that were sent during event subscription
          items:
            type: integer
          minItems: 1
          type: array
      required:
      - event
      type: object
    Event:
      anyOf:
      - $ref: '#/components/schemas/Event_anyOf'
      - description: |
          This string provides forward-compatibility with future extensions to the enumeration and is not used to encode content defined in the present version of this API.
        type: string
      description: "Possible values are:\n- SESSION_TERMINATION: Indicates that Rx\
        \ session is terminated.\n- LOSS_OF_BEARER : Indicates a loss of a bearer.\n\
        - RECOVERY_OF_BEARER: Indicates a recovery of a bearer.\n- RELEASE_OF_BEARER:\
        \ Indicates a release of a bearer.\n- USAGE_REPORT: Indicates the usage report\
        \ event. \n- FAILED_RESOURCES_ALLOCATION: Indicates the resource allocation\
        \ is failed.\n- SUCCESSFUL_RESOURCES_ALLOCATION: Indicates the resource allocation\
        \ is successful.\n"
    AccumulatedUsage:
      description: Represents an accumulated usage.
      example:
        duration: 0
        totalVolume: 0
        downlinkVolume: 0
        uplinkVolume: 0
      properties:
        duration:
          description: Unsigned integer identifying a period of time in units of seconds.
          minimum: 0
          type: integer
        totalVolume:
          description: Unsigned integer identifying a volume in units of bytes.
          format: int64
          minimum: 0
          type: integer
        downlinkVolume:
          description: Unsigned integer identifying a volume in units of bytes.
          format: int64
          minimum: 0
          type: integer
        uplinkVolume:
          description: Unsigned integer identifying a volume in units of bytes.
          format: int64
          minimum: 0
          type: integer
      type: object
    DurationSec:
      description: Unsigned integer identifying a period of time in units of seconds.
      minimum: 0
      type: integer
    Volume:
      description: Unsigned integer identifying a volume in units of bytes.
      format: int64
      minimum: 0
      type: integer
    SupportedFeatures:
      description: |
        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of "0" to "9",  "a" to "f" or "A" to "F" and shall represent the support of 4 features as described in  tableÂ 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
      pattern: "^[A-Fa-f0-9]*$"
      type: string
    Dnn:
      description: |
        String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. "Label1.Label2.Label3").
      type: string
    Snssai:
      description: |
        When Snssai needs to be converted to string (e.g. when used in maps as key), the string shall be composed of one to three digits "sst" optionally followed by "-" and 6 hexadecimal digits "sd".
      example:
        sd: sd
        sst: 20
      properties:
        sst:
          description: "Unsigned integer, within the range 0 to 255, representing\
            \ the Slice/Service Type.  It indicates the expected Network Slice behaviour\
            \ in terms of features and services. Values 0 to 127 correspond to the\
            \ standardized SST range. Values 128 to 255 correspond  to the Operator-specific\
            \ range. See clause 28.4.2 of 3GPP TS 23.003. Standardized values are\
            \ defined in clause 5.15.2.2 of 3GPP TS 23.501. \n"
          maximum: 255
          minimum: 0
          type: integer
        sd:
          description: |
            3-octet string, representing the Slice Differentiator, in hexadecimal representation. Each character in the string shall take a value of "0" to "9", "a" to "f" or "A" to "F" and shall represent 4 bits. The most significant character representing the 4 most significant bits of the SD shall appear first in the string, and the character representing the 4 least significant bit of the SD shall appear last in the string. This is an optional parameter that complements the Slice/Service type(s) to allow to  differentiate amongst multiple Network Slices of the same Slice/Service type. This IE shall be absent if no SD value is associated with the SST.
          pattern: "^[A-Fa-f0-9]{6}$"
          type: string
      required:
      - sst
      type: object
    WebsockNotifConfig:
      description: Represents the configuration information for the delivery of notifications
        over Websockets.
      example:
        requestWebsocketUri: true
        websocketUri: websocketUri
      properties:
        websocketUri:
          description: string formatted according to IETF RFC 3986 identifying a referenced
            resource.
          type: string
        requestWebsocketUri:
          description: Set by the SCS/AS to indicate that the Websocket delivery is
            requested.
          type: boolean
      type: object
    Ipv4Addr_1:
      description: string identifying a Ipv4 address formatted in the "dotted decimal"
        notation as defined in IETF RFC 1166.
      type: string
    Ipv6Addr_1:
      description: string identifying a Ipv6 address formatted according to clause
        4 in IETF RFC 5952. The mixed Ipv4 Ipv6 notation according to clause 5 of
        IETF RFC 5952 shall not be used.
      type: string
    FlowInfo:
      description: Represents IP flow information.
      example:
        flowDescriptions:
        - flowDescriptions
        - flowDescriptions
        flowId: 6
      properties:
        flowId:
          description: Indicates the IP flow identifier.
          type: integer
        flowDescriptions:
          description: |
            Indicates the packet filters of the IP flow. Refer to clause 5.3.8 of 3GPP TS 29.214 for encoding. It shall contain UL and/or DL IP flow description.
          items:
            type: string
          maxItems: 2
          minItems: 1
          type: array
      required:
      - flowId
      type: object
    EthFlowDescription:
      description: Identifies an Ethernet flow.
      example:
        destMacAddr: destMacAddr
        destMacAddrEnd: destMacAddrEnd
        sourceMacAddr: sourceMacAddr
        fDir: null
        ethType: ethType
        fDesc: fDesc
        vlanTags:
        - vlanTags
        - vlanTags
        srcMacAddrEnd: srcMacAddrEnd
      properties:
        destMacAddr:
          description: |
            String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042.
          pattern: "^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$"
          type: string
        ethType:
          type: string
        fDesc:
          description: Defines a packet filter of an IP flow.
          type: string
        fDir:
          $ref: '#/components/schemas/FlowDirection'
        sourceMacAddr:
          description: |
            String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042.
          pattern: "^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$"
          type: string
        vlanTags:
          items:
            type: string
          maxItems: 2
          minItems: 1
          type: array
        srcMacAddrEnd:
          description: |
            String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042.
          pattern: "^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$"
          type: string
        destMacAddrEnd:
          description: |
            String identifying a MAC address formatted in the hexadecimal notation according to clause 1.1 and clause 2.1 of RFC 7042.
          pattern: "^([0-9a-fA-F]{2})((-[0-9a-fA-F]{2}){5})$"
          type: string
      required:
      - ethType
      type: object
    FlowDescription:
      description: Defines a packet filter of an IP flow.
      type: string
    SponsorInformation:
      description: Represents a sponsor information.
      example:
        aspId: aspId
        sponsorId: sponsorId
      properties:
        sponsorId:
          description: It indicates Sponsor ID.
          type: string
        aspId:
          description: It indicates Application Service Provider ID.
          type: string
      required:
      - aspId
      - sponsorId
      type: object
    BdtReferenceId:
      description: string identifying a BDT Reference ID as defined in clause 5.3.3
        of 3GPP TS 29.154.
      type: string
    ServAuthInfo:
      anyOf:
      - $ref: '#/components/schemas/ServAuthInfo_anyOf'
      - description: |
          This string provides forward-compatibility with future extensions to the enumeration and is not used to encode content defined in the present version of this API.
        type: string
      description: Indicates the result of the Policy Authorization service request
        from the AF.
    UsageThreshold:
      description: Represents a usage threshold.
      example:
        duration: 0
        totalVolume: 0
        downlinkVolume: 0
        uplinkVolume: 0
      properties:
        duration:
          description: Unsigned integer identifying a period of time in units of seconds.
          minimum: 0
          type: integer
        totalVolume:
          description: Unsigned integer identifying a volume in units of bytes.
          format: int64
          minimum: 0
          type: integer
        downlinkVolume:
          description: Unsigned integer identifying a volume in units of bytes.
          format: int64
          minimum: 0
          type: integer
        uplinkVolume:
          description: Unsigned integer identifying a volume in units of bytes.
          format: int64
          minimum: 0
          type: integer
      type: object
    UsageThresholdRm:
      description: Represents the same as the UsageThreshold data type but with the
        nullable:true property.
      nullable: true
      properties:
        duration:
          description: Unsigned integer identifying a period of time in units of seconds
            with "nullable=true" property.
          minimum: 0
          nullable: true
          type: integer
        totalVolume:
          description: Unsigned integer identifying a volume in units of bytes with
            "nullable=true" property.
          format: int64
          minimum: 0
          nullable: true
          type: integer
        downlinkVolume:
          description: Unsigned integer identifying a volume in units of bytes with
            "nullable=true" property.
          format: int64
          minimum: 0
          nullable: true
          type: integer
        uplinkVolume:
          description: Unsigned integer identifying a volume in units of bytes with
            "nullable=true" property.
          format: int64
          minimum: 0
          nullable: true
          type: integer
      type: object
    DurationSecRm:
      description: Unsigned integer identifying a period of time in units of seconds
        with "nullable=true" property.
      minimum: 0
      nullable: true
      type: integer
    VolumeRm:
      description: Unsigned integer identifying a volume in units of bytes with "nullable=true"
        property.
      format: int64
      minimum: 0
      nullable: true
      type: integer
    FlowDirection:
      anyOf:
      - $ref: '#/components/schemas/FlowDirection_anyOf'
      - description: |
          This string provides forward-compatibility with future extensions to the enumeration and is not used to encode content defined in the present version of this API.
        type: string
      description: "Possible values are:\n- DOWNLINK: The corresponding filter applies\
        \ for traffic to the UE.\n- UPLINK: The corresponding filter applies for traffic\
        \ from the UE.\n- BIDIRECTIONAL: The corresponding filter applies for traffic\
        \ both to and from the UE.\n- UNSPECIFIED: The corresponding filter applies\
        \ for traffic to the UE (downlink), but has no \nspecific direction declared.\
        \ The service data flow detection shall apply the filter for \nuplink traffic\
        \ as if the filter was bidirectional. The PCF shall not use the value \nUNSPECIFIED\
        \ in filters created by the network in NW-initiated procedures. The PCF shall\
        \ only \ninclude the value UNSPECIFIED in filters in UE-initiated procedures\
        \ if the same value is \nreceived from the SMF.\n"
    Event_anyOf:
      enum:
      - SESSION_TERMINATION
      - LOSS_OF_BEARER
      - RECOVERY_OF_BEARER
      - RELEASE_OF_BEARER
      - USAGE_REPORT
      - FAILED_RESOURCES_ALLOCATION
      - SUCCESSFUL_RESOURCES_ALLOCATION
      type: string
      example: null
    ServAuthInfo_anyOf:
      enum:
      - TP_NOT_KNOWN
      - TP_EXPIRED
      - TP_NOT_YET_OCURRED
      - ROUT_REQ_NOT_AUTHORIZED
      type: string
      example: null
    FlowDirection_anyOf:
      enum:
      - DOWNLINK
      - UPLINK
      - BIDIRECTIONAL
      - UNSPECIFIED
      type: string
      example: null
  securitySchemes:
    oAuth2ClientCredentials:
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: "{tokenUrl}"
      type: oauth2
