openapi: 3.0.0
info:
  description: "API for VAE File Distribution Service  \nÂ© 2022, 3GPP Organizational\
    \ Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  \nAll rights reserved.\n"
  title: VAE_FileDistribution
  version: 1.2.0-alpha.1
externalDocs:
  description: 3GPP TS 29.486 V18.0.0 V2X Application Enabler (VAE) Services
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.486/
servers:
- url: "{apiRoot}/vae-file-distribution/v1"
  variables:
    apiRoot:
      default: https://example.com
      description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501
security:
- {}
- oAuth2ClientCredentials: []
paths:
  /file-distributions:
    post:
      operationId: CreateFileDistributions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileDistributionData'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileDistributionData'
          description: File Distribution Resource Created
          headers:
            Location:
              description: Contains the URI of the newly created resource
              explode: false
              required: true
              schema:
                type: string
              style: simple
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "411":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Length Required
        "413":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Payload Too Large
        "415":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unsupported Media Type
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
      summary: VAE File Distributions resource create service Operation
      tags:
      - file distributions collection (Document)
  /file-distributions/{distributionId}:
    delete:
      operationId: DeleteFileDistribution
      parameters:
      - description: Unique ID of the file distribution to be deleted
        explode: false
        in: path
        name: distributionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: The subscription was terminated successfully.
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "308":
          description: Permanent Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
      summary: VAE File Distribution resource delete service Operation
      tags:
      - Individual file distribution (Document)
    get:
      operationId: ReadIndividualFileDistribution
      parameters:
      - description: Identifier of a file distribution resource
        explode: false
        in: path
        name: distributionId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileDistributionData'
          description: OK. Resource representation is returned
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "308":
          description: Permanent Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "406":
          description: 406 Not Acceptable
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
      summary: Get an existing individual file distribution resource
      tags:
      - Individual File Distribution (Document)
components:
  responses:
    "400":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Bad request
    "401":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Unauthorized
    "403":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Forbidden
    "404":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Not Found
    "411":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Length Required
    "413":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Payload Too Large
    "415":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Unsupported Media Type
    "429":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Too Many Requests
    "500":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Internal Server Error
    "503":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Service Unavailable
    default:
      description: Generic Error
    "307":
      description: Temporary Redirect
      headers:
        Location:
          description: An alternative URI of the resource.
          required: true
          schema:
            type: string
    "308":
      description: Permanent Redirect
      headers:
        Location:
          description: An alternative URI of the resource.
          required: true
          schema:
            type: string
    "406":
      description: 406 Not Acceptable
  schemas:
    FileDistributionData:
      description: Represents an individual File Distribution resource for a V2X group
        ID.
      example:
        maxDelay: 0
        localMbmsInfo:
          mbmsEnbIpv6MulAddr: 2001:db8:abcd:12::0/64
          cteid: cteid
          bmscIpv6Addr: 2001:db8:85a3::8a2e:370:7334
          mbmsGwIpv4SsmAddr: 198.51.100.1
          mbmsGwIpv6SsmAddr: 2001:db8:85a3::8a2e:370:7334
          mbmsEnbIpv4MulAddr: 198.51.100.1
          bmscIpv4Addr: 198.51.100.1
          bmscPort: 0
        fileLists:
        - fileDisplayUri: fileDisplayUri
          completionTime: 2000-01-23T04:56:07.000+00:00
          fileEarFetchTime: 2000-01-23T04:56:07.000+00:00
          fileSize: 0
          fileStatus: null
          uniAvailability: true
          fileLatFetchTime: 2000-01-23T04:56:07.000+00:00
          fileUri: fileUri
          fileRepetition: 1
          keepUpdateInterval: 6
        - fileDisplayUri: fileDisplayUri
          completionTime: 2000-01-23T04:56:07.000+00:00
          fileEarFetchTime: 2000-01-23T04:56:07.000+00:00
          fileSize: 0
          fileStatus: null
          uniAvailability: true
          fileLatFetchTime: 2000-01-23T04:56:07.000+00:00
          fileUri: fileUri
          fileRepetition: 1
          keepUpdateInterval: 6
        serviceClass: serviceClass
        groupId: groupId
        geoArea: null
        maxBitrate: maxBitrate
        suppFeat: suppFeat
        localMbmsActInd: true
      properties:
        groupId:
          description: Represents the group ID for which a V2X message is addressed.
          type: string
        fileLists:
          items:
            $ref: '#/components/schemas/FileList'
          minItems: 1
          type: array
        serviceClass:
          type: string
        geoArea:
          $ref: '#/components/schemas/GeographicArea'
        maxBitrate:
          description: |
            String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
          pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
          type: string
        maxDelay:
          description: "Unsigned Integer, i.e. only value 0 and integers above 0 are\
            \ permissible."
          minimum: 0
          type: integer
        localMbmsInfo:
          $ref: '#/components/schemas/LocalMbmsInfo'
        localMbmsActInd:
          type: boolean
        suppFeat:
          description: |
            A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of "0" to "9",  "a" to "f" or "A" to "F" and shall represent the support of 4 features as described in  tableÂ 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
          pattern: "^[A-Fa-f0-9]*$"
          type: string
      required:
      - fileLists
      - geoArea
      - maxBitrate
      - maxDelay
      type: object
    FileList:
      description: Represents a file list.
      example:
        fileDisplayUri: fileDisplayUri
        completionTime: 2000-01-23T04:56:07.000+00:00
        fileEarFetchTime: 2000-01-23T04:56:07.000+00:00
        fileSize: 0
        fileStatus: null
        uniAvailability: true
        fileLatFetchTime: 2000-01-23T04:56:07.000+00:00
        fileUri: fileUri
        fileRepetition: 1
        keepUpdateInterval: 6
      properties:
        fileUri:
          description: String providing an URI formatted according to RFC 3986.
          type: string
        fileDisplayUri:
          description: String providing an URI formatted according to RFC 3986.
          type: string
        fileEarFetchTime:
          description: string with format 'date-time' as defined in OpenAPI.
          format: date-time
          type: string
        fileLatFetchTime:
          description: string with format 'date-time' as defined in OpenAPI.
          format: date-time
          type: string
        fileSize:
          description: "Unsigned Integer, i.e. only value 0 and integers above 0 are\
            \ permissible."
          minimum: 0
          type: integer
        fileStatus:
          $ref: '#/components/schemas/FileStatus'
        completionTime:
          description: string with format 'date-time' as defined in OpenAPI.
          format: date-time
          type: string
        keepUpdateInterval:
          description: indicating a time in seconds.
          type: integer
        uniAvailability:
          type: boolean
        fileRepetition:
          type: integer
      required:
      - completionTime
      - fileDisplayUri
      - fileEarFetchTime
      - fileLatFetchTime
      - fileStatus
      - fileUri
      - keepUpdateInterval
      type: object
    LocalMbmsInfo:
      description: Contains the local MBMS information.
      example:
        mbmsEnbIpv6MulAddr: 2001:db8:abcd:12::0/64
        cteid: cteid
        bmscIpv6Addr: 2001:db8:85a3::8a2e:370:7334
        mbmsGwIpv4SsmAddr: 198.51.100.1
        mbmsGwIpv6SsmAddr: 2001:db8:85a3::8a2e:370:7334
        mbmsEnbIpv4MulAddr: 198.51.100.1
        bmscIpv4Addr: 198.51.100.1
        bmscPort: 0
      properties:
        mbmsEnbIpv4MulAddr:
          description: |
            String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
          example: 198.51.100.1
          pattern: "^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$"
          type: string
        mbmsEnbIpv6MulAddr:
          $ref: '#/components/schemas/Ipv6Prefix'
        mbmsGwIpv4SsmAddr:
          description: |
            String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
          example: 198.51.100.1
          pattern: "^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$"
          type: string
        mbmsGwIpv6SsmAddr:
          $ref: '#/components/schemas/Ipv6Addr'
        cteid:
          type: string
        bmscIpv4Addr:
          description: |
            String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
          example: 198.51.100.1
          pattern: "^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$"
          type: string
        bmscIpv6Addr:
          $ref: '#/components/schemas/Ipv6Addr'
        bmscPort:
          description: "Unsigned Integer, i.e. only value 0 and integers above 0 are\
            \ permissible."
          minimum: 0
          type: integer
      type: object
    FileStatus:
      anyOf:
      - enum:
        - PENDING
        - FETCHED
        - PREPARED
        - TRANSMITTING
        - SENT
        type: string
      - description: |
          This string provides forward-compatibility with future extensions to the enumeration and is not used to encode content defined in the present version of this API.
        type: string
      description: Represents a file status.
    ProblemDetails:
      description: Provides additional information in an error response.
      properties:
        type:
          description: String providing an URI formatted according to RFC 3986.
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          description: A human-readable explanation specific to this occurrence of
            the problem.
          type: string
        instance:
          description: String providing an URI formatted according to RFC 3986.
          type: string
        cause:
          description: |
            A machine-readable application error cause specific to this occurrence of the problem.  This IE should be present and provide application-related error information, if available.
          type: string
        invalidParams:
          items:
            $ref: '#/components/schemas/InvalidParam'
          minItems: 1
          type: array
        supportedFeatures:
          description: |
            A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of "0" to "9",  "a" to "f" or "A" to "F" and shall represent the support of 4 features as described in  tableÂ 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
          pattern: "^[A-Fa-f0-9]*$"
          type: string
        accessTokenError:
          $ref: '#/components/schemas/AccessTokenErr'
        accessTokenRequest:
          $ref: '#/components/schemas/AccessTokenReq'
        nrfId:
          description: Fully Qualified Domain Name
          maxLength: 253
          minLength: 4
          pattern: "^([0-9A-Za-z]([-0-9A-Za-z]{0,61}[0-9A-Za-z])?\\.)+[A-Za-z]{2,63}\\\
            .?$"
          type: string
        supportedApiVersions:
          items:
            type: string
          minItems: 1
          type: array
      type: object
    Uri:
      description: String providing an URI formatted according to RFC 3986.
      type: string
    InvalidParam:
      description: It contains an invalid parameter and a related description.
      properties:
        param:
          description: |
            If the invalid parameter is an attribute in a JSON body, this IE shall contain the  attribute's name and shall be encoded as a JSON Pointer. If the invalid parameter is  an HTTP header, this IE shall be formatted as the concatenation of the string "header "  plus the name of such header. If the invalid parameter is a query parameter, this IE  shall be formatted as the concatenation of the string "query " plus the name of such  query parameter. If the invalid parameter is a variable part in the path of a resource  URI, this IE shall contain the name of the variable, including the symbols "{" and "}"  used in OpenAPI specification as the notation to represent variable path segments.
          type: string
        reason:
          description: |
            A human-readable reason, e.g. "must be a positive integer". In cases involving failed  operations in a PATCH request, the reason string should identify the operation that  failed using the operation's array index to assist in correlation of the invalid  parameter with the failed operation, e.g." Replacement value invalid for attribute  (failed operation index= 4)"
          type: string
      required:
      - param
      type: object
    SupportedFeatures:
      description: |
        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of "0" to "9",  "a" to "f" or "A" to "F" and shall represent the support of 4 features as described in  tableÂ 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
      pattern: "^[A-Fa-f0-9]*$"
      type: string
    Fqdn:
      description: Fully Qualified Domain Name
      maxLength: 253
      minLength: 4
      pattern: "^([0-9A-Za-z]([-0-9A-Za-z]{0,61}[0-9A-Za-z])?\\.)+[A-Za-z]{2,63}\\\
        .?$"
      type: string
    ProblemDetails_1:
      description: Represents additional information and details on an error response.
      properties:
        type:
          description: string providing an URI formatted according to IETF RFC 3986.
          type: string
        title:
          description: "A short, human-readable summary of the problem type. It should\
            \ not change from occurrence to occurrence of the problem."
          type: string
        status:
          description: The HTTP status code for this occurrence of the problem.
          type: integer
        detail:
          description: A human-readable explanation specific to this occurrence of
            the problem.
          type: string
        instance:
          description: string providing an URI formatted according to IETF RFC 3986.
          type: string
        cause:
          description: "A machine-readable application error cause specific to this\
            \ occurrence of the problem. This IE should be present and provide application-related\
            \ error information, if available."
          type: string
        invalidParams:
          description: "Description of invalid parameters, for a request rejected\
            \ due to invalid parameters."
          items:
            $ref: '#/components/schemas/InvalidParam_1'
          minItems: 1
          type: array
        supportedFeatures:
          description: |
            A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of "0" to "9",  "a" to "f" or "A" to "F" and shall represent the support of 4 features as described in  tableÂ 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
          pattern: "^[A-Fa-f0-9]*$"
          type: string
      type: object
    Uri_1:
      description: string providing an URI formatted according to IETF RFC 3986.
      type: string
    InvalidParam_1:
      description: "Represents the description of invalid parameters, for a request\
        \ rejected due to invalid parameters."
      properties:
        param:
          description: "Attribute's name encoded as a JSON Pointer, or header's name."
          type: string
        reason:
          description: "A human-readable reason, e.g. \"must be a positive integer\"\
            ."
          type: string
      required:
      - param
      type: object
    V2xGroupId:
      description: Represents the group ID for which a V2X message is addressed.
      type: string
    GeographicArea:
      anyOf:
      - $ref: '#/components/schemas/Point'
      - $ref: '#/components/schemas/PointUncertaintyCircle'
      - $ref: '#/components/schemas/PointUncertaintyEllipse'
      - $ref: '#/components/schemas/Polygon'
      - $ref: '#/components/schemas/PointAltitude'
      - $ref: '#/components/schemas/PointAltitudeUncertainty'
      - $ref: '#/components/schemas/EllipsoidArc'
      description: Geographic area specified by different shape.
    Point:
      allOf:
      - $ref: '#/components/schemas/GADShape'
      - $ref: '#/components/schemas/Point_allOf'
      description: Ellipsoid Point.
    GADShape:
      description: Common base type for GAD shapes.
      discriminator:
        mapping:
          POINT: '#/components/schemas/Point'
          POINT_UNCERTAINTY_CIRCLE: '#/components/schemas/PointUncertaintyCircle'
          POINT_UNCERTAINTY_ELLIPSE: '#/components/schemas/PointUncertaintyEllipse'
          POLYGON: '#/components/schemas/Polygon'
          POINT_ALTITUDE: '#/components/schemas/PointAltitude'
          POINT_ALTITUDE_UNCERTAINTY: '#/components/schemas/PointAltitudeUncertainty'
          ELLIPSOID_ARC: '#/components/schemas/EllipsoidArc'
          LOCAL_2D_POINT_UNCERTAINTY_ELLIPSE: '#/components/schemas/Local2dPointUncertaintyEllipse'
          LOCAL_3D_POINT_UNCERTAINTY_ELLIPSOID: '#/components/schemas/Local3dPointUncertaintyEllipsoid'
        propertyName: shape
      properties:
        shape:
          $ref: '#/components/schemas/SupportedGADShapes'
      required:
      - shape
      type: object
    SupportedGADShapes:
      anyOf:
      - enum:
        - POINT
        - POINT_UNCERTAINTY_CIRCLE
        - POINT_UNCERTAINTY_ELLIPSE
        - POLYGON
        - POINT_ALTITUDE
        - POINT_ALTITUDE_UNCERTAINTY
        - ELLIPSOID_ARC
        - LOCAL_2D_POINT_UNCERTAINTY_ELLIPSE
        - LOCAL_3D_POINT_UNCERTAINTY_ELLIPSOID
        type: string
      - type: string
      description: Indicates supported GAD shapes.
    PointUncertaintyCircle:
      allOf:
      - $ref: '#/components/schemas/GADShape'
      - $ref: '#/components/schemas/PointUncertaintyCircle_allOf'
      description: Ellipsoid point with uncertainty circle.
    GeographicalCoordinates:
      description: Geographical coordinates.
      properties:
        lon:
          format: double
          maximum: 180
          minimum: -180
          type: number
        lat:
          format: double
          maximum: 90
          minimum: -90
          type: number
      required:
      - lat
      - lon
      type: object
    Uncertainty:
      description: Indicates value of uncertainty.
      format: float
      minimum: 0
      type: number
    PointUncertaintyEllipse:
      allOf:
      - $ref: '#/components/schemas/GADShape'
      - $ref: '#/components/schemas/PointUncertaintyEllipse_allOf'
      description: Ellipsoid point with uncertainty ellipse.
    UncertaintyEllipse:
      description: Ellipse with uncertainty.
      properties:
        semiMajor:
          description: Indicates value of uncertainty.
          format: float
          minimum: 0
          type: number
        semiMinor:
          description: Indicates value of uncertainty.
          format: float
          minimum: 0
          type: number
        orientationMajor:
          description: Indicates value of orientation angle.
          maximum: 180
          minimum: 0
          type: integer
      required:
      - orientationMajor
      - semiMajor
      - semiMinor
      type: object
    Orientation:
      description: Indicates value of orientation angle.
      maximum: 180
      minimum: 0
      type: integer
    Confidence:
      description: Indicates value of confidence.
      maximum: 100
      minimum: 0
      type: integer
    Polygon:
      allOf:
      - $ref: '#/components/schemas/GADShape'
      - $ref: '#/components/schemas/Polygon_allOf'
      description: Polygon.
    PointList:
      description: List of points.
      items:
        $ref: '#/components/schemas/GeographicalCoordinates'
      maxItems: 15
      minItems: 3
      type: array
    PointAltitude:
      allOf:
      - $ref: '#/components/schemas/GADShape'
      - $ref: '#/components/schemas/PointAltitude_allOf'
      description: Ellipsoid point with altitude.
    Altitude:
      description: Indicates value of altitude.
      format: double
      maximum: 32767
      minimum: -32767
      type: number
    PointAltitudeUncertainty:
      allOf:
      - $ref: '#/components/schemas/GADShape'
      - $ref: '#/components/schemas/PointAltitudeUncertainty_allOf'
      description: Ellipsoid point with altitude and uncertainty ellipsoid.
    EllipsoidArc:
      allOf:
      - $ref: '#/components/schemas/GADShape'
      - $ref: '#/components/schemas/EllipsoidArc_allOf'
      description: Ellipsoid Arc.
    InnerRadius:
      description: Indicates value of the inner radius.
      format: int32
      maximum: 327675
      minimum: 0
      type: integer
    Angle:
      description: Indicates value of angle.
      maximum: 360
      minimum: 0
      type: integer
    Local2dPointUncertaintyEllipse:
      allOf:
      - $ref: '#/components/schemas/GADShape'
      - $ref: '#/components/schemas/Local2dPointUncertaintyEllipse_allOf'
      description: Local 2D point with uncertainty ellipse
    LocalOrigin:
      description: Indicates a Local origin in a reference system
      properties:
        coordinateId:
          type: string
        point:
          $ref: '#/components/schemas/GeographicalCoordinates'
      type: object
    RelativeCartesianLocation:
      description: Relative Cartesian Location
      properties:
        x:
          description: string with format 'float' as defined in OpenAPI.
          format: float
          type: number
        "y":
          description: string with format 'float' as defined in OpenAPI.
          format: float
          type: number
        z:
          description: string with format 'float' as defined in OpenAPI.
          format: float
          type: number
      required:
      - x
      - "y"
      type: object
    Local3dPointUncertaintyEllipsoid:
      allOf:
      - $ref: '#/components/schemas/GADShape'
      - $ref: '#/components/schemas/Local3dPointUncertaintyEllipsoid_allOf'
      description: Local 3D point with uncertainty ellipsoid
    UncertaintyEllipsoid:
      description: Ellipsoid with uncertainty
      properties:
        semiMajor:
          description: Indicates value of uncertainty.
          format: float
          minimum: 0
          type: number
        semiMinor:
          description: Indicates value of uncertainty.
          format: float
          minimum: 0
          type: number
        vertical:
          description: Indicates value of uncertainty.
          format: float
          minimum: 0
          type: number
        orientationMajor:
          description: Indicates value of orientation angle.
          maximum: 180
          minimum: 0
          type: integer
      required:
      - orientationMajor
      - semiMajor
      - semiMinor
      - vertical
      type: object
    BitRate:
      description: |
        String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix "K" is used to represent the standard symbol "k".
      pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
      type: string
    Uinteger:
      description: "Unsigned Integer, i.e. only value 0 and integers above 0 are permissible."
      minimum: 0
      type: integer
    DateTime:
      description: string with format 'date-time' as defined in OpenAPI.
      format: date-time
      type: string
    DurationSec:
      description: indicating a time in seconds.
      type: integer
    Ipv4Addr:
      description: |
        String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
      example: 198.51.100.1
      pattern: "^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$"
      type: string
    Ipv6Prefix:
      allOf:
      - pattern: "^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))(\\\
          /(([0-9])|([0-9]{2})|(1[0-1][0-9])|(12[0-8])))$"
      - pattern: "^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))(\\\
          /.+)$"
      description: |
        String identifying an IPv6 address prefix formatted according to clause 4 of RFC 5952. IPv6Prefix data type may contain an individual /128 IPv6 address.
      example: 2001:db8:abcd:12::0/64
      type: string
    Ipv6Addr:
      allOf:
      - pattern: "^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))$"
      - pattern: "^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))$"
      description: |
        String identifying an IPv6 address formatted according to clause 4 of RFC5952. The mixed IPv4 IPv6 notation according to clause 5 of RFC5952 shall not be used.
      example: 2001:db8:85a3::8a2e:370:7334
      type: string
    AccessTokenErr:
      description: Error returned in the access token response message
      properties:
        error:
          enum:
          - invalid_request
          - invalid_client
          - invalid_grant
          - unauthorized_client
          - unsupported_grant_type
          - invalid_scope
          type: string
        error_description:
          type: string
        error_uri:
          type: string
      required:
      - error
      type: object
    AccessTokenReq:
      description: Contains information related to the access token request
      properties:
        grant_type:
          enum:
          - client_credentials
          type: string
        nfInstanceId:
          description: "String uniquely identifying a NF instance. The format of the\
            \ NF Instance ID shall be a  Universally Unique Identifier (UUID) version\
            \ 4, as described in IETF RFC 4122. \n"
          format: uuid
          type: string
        nfType:
          $ref: '#/components/schemas/NFType'
        targetNfType:
          $ref: '#/components/schemas/NFType'
        scope:
          pattern: "^([a-zA-Z0-9_:-]+)( [a-zA-Z0-9_:-]+)*$"
          type: string
        targetNfInstanceId:
          description: "String uniquely identifying a NF instance. The format of the\
            \ NF Instance ID shall be a  Universally Unique Identifier (UUID) version\
            \ 4, as described in IETF RFC 4122. \n"
          format: uuid
          type: string
        requesterPlmn:
          $ref: '#/components/schemas/PlmnId'
        requesterPlmnList:
          items:
            $ref: '#/components/schemas/PlmnId'
          minItems: 2
          type: array
        requesterSnssaiList:
          items:
            $ref: '#/components/schemas/Snssai'
          minItems: 1
          type: array
        requesterFqdn:
          description: Fully Qualified Domain Name
          maxLength: 253
          minLength: 4
          pattern: "^([0-9A-Za-z]([-0-9A-Za-z]{0,61}[0-9A-Za-z])?\\.)+[A-Za-z]{2,63}\\\
            .?$"
          type: string
        requesterSnpnList:
          items:
            $ref: '#/components/schemas/PlmnIdNid'
          minItems: 1
          type: array
        targetPlmn:
          $ref: '#/components/schemas/PlmnId'
        targetSnpn:
          $ref: '#/components/schemas/PlmnIdNid'
        targetSnssaiList:
          items:
            $ref: '#/components/schemas/Snssai'
          minItems: 1
          type: array
        targetNsiList:
          items:
            type: string
          minItems: 1
          type: array
        targetNfSetId:
          description: "NF Set Identifier (see clause 28.12 of 3GPP TS 23.003), formatted\
            \ as the following string \"set<Set ID>.<nftype>set.5gc.mnc<MNC>.mcc<MCC>\"\
            , or  \"set<SetID>.<NFType>set.5gc.nid<NID>.mnc<MNC>.mcc<MCC>\" with \
            \ <MCC> encoded as defined in clause 5.4.2 (\"Mcc\" data type definition)\
            \  <MNC> encoding the Mobile Network Code part of the PLMN, comprising\
            \ 3 digits. \n  If there are only 2 significant digits in the MNC, one\
            \ \"0\" digit shall be inserted \n  at the left side to fill the 3 digits\
            \ coding of MNC.  Pattern: '^[0-9]{3}$'\n<NFType> encoded as a value defined\
            \ in Table 6.1.6.3.3-1 of 3GPP TS 29.510 but \n  with lower case characters\
            \ <Set ID> encoded as a string of characters consisting of \n  alphabetic\
            \ characters (A-Z and a-z), digits (0-9) and/or the hyphen (-) and that\
            \ \n  shall end with either an alphabetic character or a digit. \n"
          type: string
        targetNfServiceSetId:
          description: "NF Service Set Identifier (see clause 28.12 of 3GPP TS 23.003)\
            \ formatted as the following  string \"set<Set ID>.sn<Service Name>.nfi<NF\
            \ Instance ID>.5gc.mnc<MNC>.mcc<MCC>\", or  \"set<SetID>.sn<ServiceName>.nfi<NFInstanceID>.5gc.nid<NID>.mnc<MNC>.mcc<MCC>\"\
            \ with  <MCC> encoded as defined in clause 5.4.2 (\"Mcc\" data type definition)\
            \   <MNC> encoding the Mobile Network Code part of the PLMN, comprising\
            \ 3 digits. \n  If there are only 2 significant digits in the MNC, one\
            \ \"0\" digit shall be inserted \n  at the left side to fill the 3 digits\
            \ coding of MNC.  Pattern: '^[0-9]{3}$'\n<NID> encoded as defined in clause\_\
            5.4.2 (\"Nid\" data type definition)  <NFInstanceId> encoded as defined\
            \ in clause 5.3.2  <ServiceName> encoded as defined in 3GPP TS 29.510\
            \  <Set ID> encoded as a string of characters consisting of alphabetic\
            \ \n  characters (A-Z and a-z), digits (0-9) and/or the hyphen (-) and\
            \ that shall end \n  with either an alphabetic character or a digit.\n"
          type: string
        hnrfAccessTokenUri:
          description: String providing an URI formatted according to RFC 3986.
          type: string
        sourceNfInstanceId:
          description: "String uniquely identifying a NF instance. The format of the\
            \ NF Instance ID shall be a  Universally Unique Identifier (UUID) version\
            \ 4, as described in IETF RFC 4122. \n"
          format: uuid
          type: string
      required:
      - grant_type
      - nfInstanceId
      - scope
      type: object
    Float:
      description: string with format 'float' as defined in OpenAPI.
      format: float
      type: number
    NfInstanceId:
      description: "String uniquely identifying a NF instance. The format of the NF\
        \ Instance ID shall be a  Universally Unique Identifier (UUID) version 4,\
        \ as described in IETF RFC 4122. \n"
      format: uuid
      type: string
    NFType:
      anyOf:
      - enum:
        - NRF
        - UDM
        - AMF
        - SMF
        - AUSF
        - NEF
        - PCF
        - SMSF
        - NSSF
        - UDR
        - LMF
        - GMLC
        - 5G_EIR
        - SEPP
        - UPF
        - N3IWF
        - AF
        - UDSF
        - BSF
        - CHF
        - NWDAF
        - PCSCF
        - CBCF
        - HSS
        - UCMF
        - SOR_AF
        - SPAF
        - MME
        - SCSAS
        - SCEF
        - SCP
        - NSSAAF
        - ICSCF
        - SCSCF
        - DRA
        - IMS_AS
        - AANF
        - 5G_DDNMF
        - NSACF
        - MFAF
        - EASDF
        - DCCF
        - MB_SMF
        - TSCTSF
        - ADRF
        - GBA_BSF
        - CEF
        - MB_UPF
        - NSWOF
        - PKMF
        - MNPF
        - SMS_GMSC
        - SMS_IWMSC
        - MBSF
        - MBSTF
        - PANF
        type: string
      - type: string
      description: NF types known to NRF
    PlmnId:
      description: |
        When PlmnId needs to be converted to string (e.g. when used in maps as key), the string  shall be composed of three digits "mcc" followed by "-" and two or three digits "mnc".
      properties:
        mcc:
          description: "Mobile Country Code part of the PLMN, comprising 3 digits,\
            \ as defined in clause 9.3.3.5 of 3GPP TS 38.413. \n"
          pattern: "^\\d{3}$"
          type: string
        mnc:
          description: "Mobile Network Code part of the PLMN, comprising 2 or 3 digits,\
            \ as defined in clause 9.3.3.5 of 3GPP TS 38.413."
          pattern: "^\\d{2,3}$"
          type: string
      required:
      - mcc
      - mnc
      type: object
    Mcc:
      description: "Mobile Country Code part of the PLMN, comprising 3 digits, as\
        \ defined in clause 9.3.3.5 of 3GPP TS 38.413. \n"
      pattern: "^\\d{3}$"
      type: string
    Mnc:
      description: "Mobile Network Code part of the PLMN, comprising 2 or 3 digits,\
        \ as defined in clause 9.3.3.5 of 3GPP TS 38.413."
      pattern: "^\\d{2,3}$"
      type: string
    Snssai:
      description: |
        When Snssai needs to be converted to string (e.g. when used in maps as key), the string shall be composed of one to three digits "sst" optionally followed by "-" and 6 hexadecimal digits "sd".
      properties:
        sst:
          description: "Unsigned integer, within the range 0 to 255, representing\
            \ the Slice/Service Type.  It indicates the expected Network Slice behaviour\
            \ in terms of features and services. Values 0 to 127 correspond to the\
            \ standardized SST range. Values 128 to 255 correspond  to the Operator-specific\
            \ range. See clause 28.4.2 of 3GPP TS 23.003. Standardized values are\
            \ defined in clause 5.15.2.2 of 3GPP TS 23.501. \n"
          maximum: 255
          minimum: 0
          type: integer
        sd:
          description: |
            3-octet string, representing the Slice Differentiator, in hexadecimal representation. Each character in the string shall take a value of "0" to "9", "a" to "f" or "A" to "F" and shall represent 4 bits. The most significant character representing the 4 most significant bits of the SD shall appear first in the string, and the character representing the 4 least significant bit of the SD shall appear last in the string. This is an optional parameter that complements the Slice/Service type(s) to allow to  differentiate amongst multiple Network Slices of the same Slice/Service type. This IE shall be absent if no SD value is associated with the SST.
          pattern: "^[A-Fa-f0-9]{6}$"
          type: string
      required:
      - sst
      type: object
    PlmnIdNid:
      description: |
        Contains the serving core network operator PLMN ID and, for an SNPN, the NID that together with the PLMN ID identifies the SNPN.
      properties:
        mcc:
          description: "Mobile Country Code part of the PLMN, comprising 3 digits,\
            \ as defined in clause 9.3.3.5 of 3GPP TS 38.413. \n"
          pattern: "^\\d{3}$"
          type: string
        mnc:
          description: "Mobile Network Code part of the PLMN, comprising 2 or 3 digits,\
            \ as defined in clause 9.3.3.5 of 3GPP TS 38.413."
          pattern: "^\\d{2,3}$"
          type: string
        nid:
          description: "This represents the Network Identifier, which together with\
            \ a PLMN ID is used to identify an SNPN (see 3GPP TS 23.003 and 3GPP TS\
            \ 23.501 clause 5.30.2.1). \n"
          pattern: "^[A-Fa-f0-9]{11}$"
          type: string
      required:
      - mcc
      - mnc
      type: object
    Nid:
      description: "This represents the Network Identifier, which together with a\
        \ PLMN ID is used to identify an SNPN (see 3GPP TS 23.003 and 3GPP TS 23.501\
        \ clause 5.30.2.1). \n"
      pattern: "^[A-Fa-f0-9]{11}$"
      type: string
    NfSetId:
      description: "NF Set Identifier (see clause 28.12 of 3GPP TS 23.003), formatted\
        \ as the following string \"set<Set ID>.<nftype>set.5gc.mnc<MNC>.mcc<MCC>\"\
        , or  \"set<SetID>.<NFType>set.5gc.nid<NID>.mnc<MNC>.mcc<MCC>\" with  <MCC>\
        \ encoded as defined in clause 5.4.2 (\"Mcc\" data type definition)  <MNC>\
        \ encoding the Mobile Network Code part of the PLMN, comprising 3 digits.\
        \ \n  If there are only 2 significant digits in the MNC, one \"0\" digit shall\
        \ be inserted \n  at the left side to fill the 3 digits coding of MNC.  Pattern:\
        \ '^[0-9]{3}$'\n<NFType> encoded as a value defined in Table 6.1.6.3.3-1 of\
        \ 3GPP TS 29.510 but \n  with lower case characters <Set ID> encoded as a\
        \ string of characters consisting of \n  alphabetic characters (A-Z and a-z),\
        \ digits (0-9) and/or the hyphen (-) and that \n  shall end with either an\
        \ alphabetic character or a digit. \n"
      type: string
    NfServiceSetId:
      description: "NF Service Set Identifier (see clause 28.12 of 3GPP TS 23.003)\
        \ formatted as the following  string \"set<Set ID>.sn<Service Name>.nfi<NF\
        \ Instance ID>.5gc.mnc<MNC>.mcc<MCC>\", or  \"set<SetID>.sn<ServiceName>.nfi<NFInstanceID>.5gc.nid<NID>.mnc<MNC>.mcc<MCC>\"\
        \ with  <MCC> encoded as defined in clause 5.4.2 (\"Mcc\" data type definition)\
        \   <MNC> encoding the Mobile Network Code part of the PLMN, comprising 3\
        \ digits. \n  If there are only 2 significant digits in the MNC, one \"0\"\
        \ digit shall be inserted \n  at the left side to fill the 3 digits coding\
        \ of MNC.  Pattern: '^[0-9]{3}$'\n<NID> encoded as defined in clause\_5.4.2\
        \ (\"Nid\" data type definition)  <NFInstanceId> encoded as defined in clause\
        \ 5.3.2  <ServiceName> encoded as defined in 3GPP TS 29.510  <Set ID> encoded\
        \ as a string of characters consisting of alphabetic \n  characters (A-Z and\
        \ a-z), digits (0-9) and/or the hyphen (-) and that shall end \n  with either\
        \ an alphabetic character or a digit.\n"
      type: string
    Point_allOf:
      properties:
        point:
          $ref: '#/components/schemas/GeographicalCoordinates'
      required:
      - point
      type: object
      example: null
    PointUncertaintyCircle_allOf:
      properties:
        point:
          $ref: '#/components/schemas/GeographicalCoordinates'
        uncertainty:
          description: Indicates value of uncertainty.
          format: float
          minimum: 0
          type: number
      required:
      - point
      - uncertainty
      type: object
      example: null
    PointUncertaintyEllipse_allOf:
      properties:
        point:
          $ref: '#/components/schemas/GeographicalCoordinates'
        uncertaintyEllipse:
          $ref: '#/components/schemas/UncertaintyEllipse'
        confidence:
          description: Indicates value of confidence.
          maximum: 100
          minimum: 0
          type: integer
      required:
      - confidence
      - point
      - uncertaintyEllipse
      type: object
      example: null
    Polygon_allOf:
      properties:
        pointList:
          description: List of points.
          items:
            $ref: '#/components/schemas/GeographicalCoordinates'
          maxItems: 15
          minItems: 3
          type: array
      required:
      - pointList
      type: object
      example: null
    PointAltitude_allOf:
      properties:
        point:
          $ref: '#/components/schemas/GeographicalCoordinates'
        altitude:
          description: Indicates value of altitude.
          format: double
          maximum: 32767
          minimum: -32767
          type: number
      required:
      - altitude
      - point
      type: object
      example: null
    PointAltitudeUncertainty_allOf:
      properties:
        point:
          $ref: '#/components/schemas/GeographicalCoordinates'
        altitude:
          description: Indicates value of altitude.
          format: double
          maximum: 32767
          minimum: -32767
          type: number
        uncertaintyEllipse:
          $ref: '#/components/schemas/UncertaintyEllipse'
        uncertaintyAltitude:
          description: Indicates value of uncertainty.
          format: float
          minimum: 0
          type: number
        confidence:
          description: Indicates value of confidence.
          maximum: 100
          minimum: 0
          type: integer
      required:
      - altitude
      - confidence
      - point
      - uncertaintyAltitude
      - uncertaintyEllipse
      type: object
      example: null
    EllipsoidArc_allOf:
      properties:
        point:
          $ref: '#/components/schemas/GeographicalCoordinates'
        innerRadius:
          description: Indicates value of the inner radius.
          format: int32
          maximum: 327675
          minimum: 0
          type: integer
        uncertaintyRadius:
          description: Indicates value of uncertainty.
          format: float
          minimum: 0
          type: number
        offsetAngle:
          description: Indicates value of angle.
          maximum: 360
          minimum: 0
          type: integer
        includedAngle:
          description: Indicates value of angle.
          maximum: 360
          minimum: 0
          type: integer
        confidence:
          description: Indicates value of confidence.
          maximum: 100
          minimum: 0
          type: integer
      required:
      - confidence
      - includedAngle
      - innerRadius
      - offsetAngle
      - point
      - uncertaintyRadius
      type: object
      example: null
    Local2dPointUncertaintyEllipse_allOf:
      properties:
        localOrigin:
          $ref: '#/components/schemas/LocalOrigin'
        point:
          $ref: '#/components/schemas/RelativeCartesianLocation'
        uncertaintyEllipse:
          $ref: '#/components/schemas/UncertaintyEllipse'
        confidence:
          description: Indicates value of confidence.
          maximum: 100
          minimum: 0
          type: integer
      required:
      - confidence
      - localOrigin
      - point
      - uncertaintyEllipse
      type: object
      example: null
    Local3dPointUncertaintyEllipsoid_allOf:
      properties:
        localOrigin:
          $ref: '#/components/schemas/LocalOrigin'
        point:
          $ref: '#/components/schemas/RelativeCartesianLocation'
        uncertaintyEllipsoid:
          $ref: '#/components/schemas/UncertaintyEllipsoid'
        confidence:
          description: Indicates value of confidence.
          maximum: 100
          minimum: 0
          type: integer
      required:
      - confidence
      - localOrigin
      - point
      - uncertaintyEllipsoid
      type: object
      example: null
  securitySchemes:
    oAuth2ClientCredentials:
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: "{tokenUrl}"
      type: oauth2
