openapi: 3.0.0
info:
  description: "API for Location Privacy Indication Parameters Provisioning.  \nÂ©\
    \ 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).\
    \  \nAll rights reserved.\n"
  title: 3gpp-lpi-pp
  version: 1.1.2
externalDocs:
  description: |
    3GPP TS 29.522 V17.8.0; 5G System; Network Exposure Function Northbound APIs.
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.522/
servers:
- url: "{apiRoot}/3gpp-lpi-pp/v1"
  variables:
    apiRoot:
      default: https://example.com
      description: apiRoot as defined in clause 5.2.4 of 3GPP TS 29.122.
security:
- {}
- oAuth2ClientCredentials: []
paths:
  /{afId}/provisionedLpis:
    get:
      operationId: ReadAllResources
      parameters:
      - description: Identifier of the AF
        explode: false
        in: path
        name: afId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/LpiParametersProvision'
                type: array
          description: OK (Successful get all of the active resources for the AF)
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "308":
          description: Permanent Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "406":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Acceptable
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
      summary: read all of the active LPI Parameters Provisioning resources for the
        AF
      tags:
      - LPI Parameters Provisionings
    post:
      operationId: CreateNewResource
      parameters:
      - description: Identifier of the AF
        explode: false
        in: path
        name: afId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LpiParametersProvision'
        description: new resource creation
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LpiParametersProvision'
          description: Created (Successful creation)
          headers:
            Location:
              description: Contains the URI of the newly created resource.
              explode: false
              required: true
              schema:
                type: string
              style: simple
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "411":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Length Required
        "413":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Payload Too Large
        "415":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unsupported Media Type
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
      summary: Creates a new LPI Parameters Provisioning resource
      tags:
      - LPI Parameters Provisionings
  /{afId}/provisionedLpis/{provisionedLpiId}:
    delete:
      operationId: DeleteAnResource
      parameters:
      - description: Identifier of the AF
        explode: false
        in: path
        name: afId
        required: true
        schema:
          type: string
        style: simple
      - description: Identifier of the provisioned LPI parameter resource
        explode: false
        in: path
        name: provisionedLpiId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: No Content (Successful deletion of the existing resource)
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "308":
          description: Permanent Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
      summary: Deletes an already existing LPI Parameters Provisioning resource
      tags:
      - Individual LPI Parameters Provisioning
    get:
      operationId: ReadAnResource
      parameters:
      - description: Identifier of the AF
        explode: false
        in: path
        name: afId
        required: true
        schema:
          type: string
        style: simple
      - description: Identifier of the provisioned LPI parameter resource
        explode: false
        in: path
        name: provisionedLpiId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LpiParametersProvision'
          description: OK (Successful get the active resource)
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "308":
          description: Permanent Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "406":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Acceptable
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
      summary: read an active LPI Parameters Provisioning resource for the AF and
        the provisioned LPI Id
      tags:
      - Individual LPI Parameters Provisioning
    patch:
      operationId: PartialUpdateAnResource
      parameters:
      - description: Identifier of the AF
        explode: false
        in: path
        name: afId
        required: true
        schema:
          type: string
        style: simple
      - description: Identifier of the provisioned LPI parameter resource
        explode: false
        in: path
        name: provisionedLpiId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LpiParametersProvisionPatch'
        description: Parameters to modify the existing resource.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LpiParametersProvision'
          description: |
            OK. The resource has been successfully modified and a representation of the  updated resource is returned.
        "204":
          description: |
            Successful case. The resource has been successfully modified and no additional content  is sent in the response message.
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "308":
          description: Permanent Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "411":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Length Required
        "413":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Payload Too Large
        "415":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unsupported Media Type
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
      summary: Partially modifies an existing LPI Parameters Provisioning resource.
      tags:
      - Individual LPI Parameters Provisioning
    put:
      operationId: FullyUpdateAnResource
      parameters:
      - description: Identifier of the AF
        explode: false
        in: path
        name: afId
        required: true
        schema:
          type: string
        style: simple
      - description: Identifier of the provisioned LPI parameter resource
        explode: false
        in: path
        name: provisionedLpiId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LpiParametersProvision'
        description: Parameters to update/replace the existing resource
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LpiParametersProvision'
          description: |
            OK. The resource has been successfully updated and a representation of the updated  resource is returned.
        "204":
          description: |
            Successful case. The resource has been successfully updated and no additional content is sent in the response message.
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "308":
          description: Permanent Redirect
          headers:
            Location:
              description: An alternative URI of the resource.
              required: true
              schema:
                type: string
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "411":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Length Required
        "413":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Payload Too Large
        "415":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unsupported Media Type
        "429":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Too Many Requests
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Internal Server Error
        "503":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Service Unavailable
        default:
          description: Generic Error
      summary: Fully updates/replaces an existing LPI Parameters Provisioning resource
      tags:
      - Individual LPI Parameters Provisioning
components:
  responses:
    "307":
      description: Temporary Redirect
      headers:
        Location:
          description: An alternative URI of the resource.
          required: true
          schema:
            type: string
    "308":
      description: Permanent Redirect
      headers:
        Location:
          description: An alternative URI of the resource.
          required: true
          schema:
            type: string
    "400":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Bad request
    "401":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Unauthorized
    "403":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Forbidden
    "404":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Not Found
    "406":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Not Acceptable
    "429":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Too Many Requests
    "500":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Internal Server Error
    "503":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Service Unavailable
    default:
      description: Generic Error
    "411":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Length Required
    "413":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Payload Too Large
    "415":
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
      description: Unsupported Media Type
  schemas:
    LpiParametersProvision:
      description: Represents an individual LPI Parameters Provisionings resource.
      example:
        exterGroupId: exterGroupId
        lpi:
          validTimePeriod:
            startTime: 2000-01-23T04:56:07.000+00:00
            endTime: 2000-01-23T04:56:07.000+00:00
          locationPrivacyInd: null
        self: self
        mtcProviderId: mtcProviderId
        suppFeat: suppFeat
        gpsi: gpsi
      properties:
        self:
          description: string formatted according to IETF RFC 3986 identifying a referenced
            resource.
          type: string
        exterGroupId:
          description: string containing a local identifier followed by "@" and a
            domain identifier. Both the local identifier and the domain identifier
            shall be encoded as strings that do not contain any "@" characters. See
            Clauses 4.6.2 and 4.6.3 of 3GPP TS 23.682 for more information.
          type: string
        gpsi:
          description: "String identifying a Gpsi shall contain either an External\
            \ Id or an MSISDN.  It shall be formatted as follows -External Identifier=\
            \ \"extid-'extid', where 'extid'  shall be formatted according to clause\
            \ 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier. \n"
          pattern: "^(msisdn-[0-9]{5,15}|extid-[^@]+@[^@]+|.+)$"
          type: string
        lpi:
          $ref: '#/components/schemas/Lpi'
        mtcProviderId:
          description: String uniquely identifying MTC provider information.
          type: string
        suppFeat:
          description: |
            A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of "0" to "9",  "a" to "f" or "A" to "F" and shall represent the support of 4 features as described in  tableÂ 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
          pattern: "^[A-Fa-f0-9]*$"
          type: string
      required:
      - lpi
      - suppFeat
      type: object
    LpiParametersProvisionPatch:
      description: Represents the parameters to modify an existing Individual LPI
        Parameters Provisionings resource.
      example:
        lpi:
          validTimePeriod:
            startTime: 2000-01-23T04:56:07.000+00:00
            endTime: 2000-01-23T04:56:07.000+00:00
          locationPrivacyInd: null
        mtcProviderId: mtcProviderId
      properties:
        lpi:
          $ref: '#/components/schemas/Lpi'
        mtcProviderId:
          description: String uniquely identifying MTC provider information.
          type: string
      type: object
    ProblemDetails:
      description: Represents additional information and details on an error response.
      properties:
        type:
          description: string providing an URI formatted according to IETF RFC 3986.
          type: string
        title:
          description: "A short, human-readable summary of the problem type. It should\
            \ not change from occurrence to occurrence of the problem."
          type: string
        status:
          description: The HTTP status code for this occurrence of the problem.
          type: integer
        detail:
          description: A human-readable explanation specific to this occurrence of
            the problem.
          type: string
        instance:
          description: string providing an URI formatted according to IETF RFC 3986.
          type: string
        cause:
          description: "A machine-readable application error cause specific to this\
            \ occurrence of the problem. This IE should be present and provide application-related\
            \ error information, if available."
          type: string
        invalidParams:
          description: "Description of invalid parameters, for a request rejected\
            \ due to invalid parameters."
          items:
            $ref: '#/components/schemas/InvalidParam'
          minItems: 1
          type: array
        supportedFeatures:
          description: |
            A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of "0" to "9",  "a" to "f" or "A" to "F" and shall represent the support of 4 features as described in  tableÂ 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
          pattern: "^[A-Fa-f0-9]*$"
          type: string
      type: object
    Uri:
      description: string providing an URI formatted according to IETF RFC 3986.
      type: string
    InvalidParam:
      description: "Represents the description of invalid parameters, for a request\
        \ rejected due to invalid parameters."
      properties:
        param:
          description: "Attribute's name encoded as a JSON Pointer, or header's name."
          type: string
        reason:
          description: "A human-readable reason, e.g. \"must be a positive integer\"\
            ."
          type: string
      required:
      - param
      type: object
    Link:
      description: string formatted according to IETF RFC 3986 identifying a referenced
        resource.
      type: string
    ExternalGroupId:
      description: string containing a local identifier followed by "@" and a domain
        identifier. Both the local identifier and the domain identifier shall be encoded
        as strings that do not contain any "@" characters. See Clauses 4.6.2 and 4.6.3
        of 3GPP TS 23.682 for more information.
      type: string
    Gpsi:
      description: "String identifying a Gpsi shall contain either an External Id\
        \ or an MSISDN.  It shall be formatted as follows -External Identifier= \"\
        extid-'extid', where 'extid'  shall be formatted according to clause 19.7.2\
        \ of 3GPP TS 23.003 that describes an  External Identifier. \n"
      pattern: "^(msisdn-[0-9]{5,15}|extid-[^@]+@[^@]+|.+)$"
      type: string
    Lpi:
      example:
        validTimePeriod:
          startTime: 2000-01-23T04:56:07.000+00:00
          endTime: 2000-01-23T04:56:07.000+00:00
        locationPrivacyInd: null
      properties:
        locationPrivacyInd:
          $ref: '#/components/schemas/LocationPrivacyInd'
        validTimePeriod:
          $ref: '#/components/schemas/ValidTimePeriod'
      required:
      - locationPrivacyInd
      type: object
    LocationPrivacyInd:
      anyOf:
      - $ref: '#/components/schemas/LocationPrivacyInd_anyOf'
      - type: string
    ValidTimePeriod:
      example:
        startTime: 2000-01-23T04:56:07.000+00:00
        endTime: 2000-01-23T04:56:07.000+00:00
      properties:
        startTime:
          description: string with format 'date-time' as defined in OpenAPI.
          format: date-time
          type: string
        endTime:
          description: string with format 'date-time' as defined in OpenAPI.
          format: date-time
          type: string
      type: object
    MtcProviderInformation:
      description: String uniquely identifying MTC provider information.
      type: string
    SupportedFeatures:
      description: |
        A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of "0" to "9",  "a" to "f" or "A" to "F" and shall represent the support of 4 features as described in  tableÂ 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
      pattern: "^[A-Fa-f0-9]*$"
      type: string
    DateTime:
      description: string with format 'date-time' as defined in OpenAPI.
      format: date-time
      type: string
    LocationPrivacyInd_anyOf:
      enum:
      - LOCATION_DISALLOWED
      - LOCATION_ALLOWED
      type: string
      example: null
  securitySchemes:
    oAuth2ClientCredentials:
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: "{tokenUrl}"
      type: oauth2
